### ISSUE TITLE
chart: functionality: manufacturing deals

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/aftershocks_data#45]
"Map: Manufacturing deals by country:
- when you click on a country, the popup has two scrollies, one of which does nothing. Although, when I drag to my laptop screen over my monitor (i.e. to a smaller screen), this second scrolly disapears. 
- No data download button. "

**Comment by jm-rivera** [comment]
@lpicci96 would you mind having a look? I haven't seen the issue but ask @Mattie-P if needed

**Comment by lpicci96** [comment]
@jm-rivera this is the issue, but it renders fine on the chart object preview



![Image](https://user-images.githubusercontent.com/56567716/197481264-c3b572ca-2e9b-4aad-b79f-9e8c57839572.png)

**Comment by jm-rivera** [comment]
ah... It's because the map is smaller than the size of the pop up (specified on flourish). Can you make the object slightly taller? (or the pop up slightly smaller (though some info may get hidden if you do that))

**Comment by lpicci96** [comment]
changed height to 700 and increased panel height proportion to 85%

**Comment by jm-rivera** [comment]
did it fix it?
